### ISSUE TITLE
contains external php-jws lib with no licence/attribution/version?

### ISSUE THREAD

**Issue by danmarsden** [CharityLearning/moodle-mod_clearlessons#6]
when including and distributing an external library you need to be careful to retain the licensing information and attribute the original authors.

you should also be adding a thirdpartylibs.xml file:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by joshwillcock** [comment]
Hello @danmarsden 

Is the Third Party Libs xml file all that is required - the external library is MIT license. I believe commit 65a84df4cff9529db892da4eed2a635392af5f19 covers this now?

**Comment by danmarsden** [comment]
You will need to drop the license file in there from their original repo - it states:

"The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

I'd also probably add a readme file in that dir that includes a link to the original repo too.

**Comment by joshwillcock** [comment]
Thank-you for your Advice Dan. I have done this now. Although I have been working with Moodle for a few years this is the first time I've ventured into using third party libraries, rather straight forward when you're explained it. Thankyou!
